name: Issue アサイン時にラベルと番号を取得

on:
  issue:
    types: [assigned]

jobs:
  get-issue-number-and-labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issue_number = github.context.payload.issue.number;
            const labels = github.context.payload.issue.labels.map(label => label.name);
            console.log(`Issue 番号: ${issue_number}`);
            console.log(`ラベル: ${labels}`);
